class AlreadyInUse(Exception):
    pass


class NotFoundCommand(Exception):
    pass